apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  template:
    spec:
      containers:
      - name: todo-backend
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10