name: Cache Node and NPM dependencies
description: |
  This action caches Node and NPM dependencies to speed up the workflow execution.
  It uses the `actions/cache` action to cache the dependencies based on the hash of the `package-lock.json` file.
  The cache is restored if it exists, otherwise, it is created and saved for future runs.

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '18.x'
  working-directory:
    description: 'Working directory for the action'
    required: false
    default: '.'



runs:
  using: "composite"
  steps:
    - name: Setup Node.js Version ${{ inputs.node-version  }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.working-directory }}/node_modules
        key: node-modules-${{ hashFiles(format('{0}/{1}',inputs.working-directory , 'package-lock.json')) }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm ci