---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-backend-secret
spec:
  encryptedData:
    jwt-secret: AgAuPISA/f4S1wBu921yqpZK4UE4eW5YSAJS/GhZueaiqeTdpEQtk8JEPpSv+vDQIlYi+WF839KnTjKULOTvpWnpVS+HhZ0mVN0HYsmxKOr/E0MAkmKnY+0FQRuweJzNqcYsVhw+CiPsLFhq5o6AROvDycNC/YrzbfjNoKJauMFYr63yooVByX/Rn2Q2CVCbK1IoXtvFw2Eo1O3NiVM9ACvi+57UwLncfj10CUVy/DlBx+cqeMLfiUXwik0aPZnVnb39/t+L2T85BJbQbSuV5d3GLxLMCvYWeqV4Y5g9ai7F1oB5fj18AZ2qcSkA1PwO8Wi3ZNnOkNs7rsOcvDaepmSN6J80ueAF2FD8mbo6O0FllS6yuXthAU10oONTgTnKILNB1ZECt7+Pt9XpB8UqgQaPqIxsW/H4AhtYKMZBvOyBFum7QZYFNySc4yGaYlat+saaaKhOXNQGgBjDxMqROcUXLSoGwWNx5hAlDFTNYfTA+X+32fEQTOy4IZenilMKya9+42vh3z+LuuezDbGKQ+bGiW5nKFQLJ4C7YkjVrIfSg2IfkW0cfCSLNkLk4hEFhN+7TB+gzcjSUafFuHpBN8RnuQ7JdYAz/RdN1IUiv6oFuTnYbzN5+5QXeZDaup47n089EpuTg1RZTCEp/z5PmUs0/Lq1W0g3lTXlqsigScZTjYLFxfDg67PEJ1tLAZjHZqukUcYzZAKD3jngwiHdM2IX7bRBwA==
  template:
    metadata:
      creationTimestamp: null
      name: todo-backend-secret
      labels:
        app: todo-backend
