---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-backend-secret
  namespace: todo-prod
spec:
  encryptedData:
    jwt-secret: AgCoJ4gwXFKy/1wdxtBcop5jFajJuLrL0F9YdNJeGO1s4DaK5OJ3MSB8irbMYoDufIlAT9xUEYC5JE8f766RAlK6EQIXwVeldqTAYFqO/rE6ukz5phY60D10LqqxdoVT994Vi+IAnflxjxbRcXc3pYqbFQkTSuEQxj5qfCYnLIf5PknDKyqVJVmpS+BOZQHduVZEWgRuJHyRgugg1mcSHO5qI7HlrrwdWLcbgnTNHTKjoYyBbSuVlG2Ln6Vydr2K0YBWzsg9jnFmbGp0z7LtUYaAB3Dh6dLrIiRnwsynkNQcrsqc91zDN9gGxLK/pYjGj3WtAgRBu/X/gpbf3xgBSsogFHgDcLNb2e1fpks3znINKQyRq2hocPJvGYke9T8pxki1Z9vnyJHOJGrcZVR2plRYLtqh2ESVDaX5lhb0kNN8eK2y71JOhnDvJdmf34BWa2jh0dJBy+zHINsTDSbm3hgAmMCb9RhQL7zGLk7dshTqhJmWGshktRwT9D0iMttsJss11nQGgGTjwTbWd+kn2AD0vYzDNMVDt6diT+CvB5/lrjezK7sWMlSVmE7PeJa0CA36h7fqMXTUwY2BWvIgDG9aE3b/K9w6BxKraLzoiUu70Fh8ADDqmQtLbrihcxaHj4/ProkX6nuymsveG2OAo1w21uJymoCnnSzxjWniCHX2KJhBKHUVYTfWF/xKvKse1pC62gPrw0mPzZ/XDhl5KXAu3rPbY8qWZAkvQhomscQ=
  template:
    metadata:
      creationTimestamp: null
      name: todo-backend-secret
      namespace: todo-prod
